version: "3"

services:
  ogame:
    env_file: .env
    container_name: ogame
    build: .
    tty: true
    volumes:
      - .:/code

  rabbit:
    image: rabbitmq:3.7.18-management-alpine
    hostname: rabbit
    container_name: rabbit
    env_file: .env
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: always

  slave:
    build: .
    env_file: .env
    restart: always
    hostname: slave
    container_name: slave
    volumes:
      - .:/code
    command: celery -A utils.app worker -B -l INFO
    depends_on:
      - rabbit
      - ogame
